In [1]:
import numpy as np

scaler = np.array(42)
scaler

array(42)

In [2]:
type(scaler)

numpy.ndarray

In [3]:
numbers = np.array([10, 20, 30])
type(numbers[0])

numpy.int64

In [4]:
temperatures = np.array([36.2, 36.7, 37.1])
type(temperatures[0])

numpy.float64

# Attributes

In [5]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [6]:
arr.shape

(2, 3)

In [7]:
arr.size

6

In [8]:
len(arr)

2

In [9]:
arr.ndim

2

In [10]:
arr.dtype

dtype('int64')

In [11]:
arr.itemsize

8

In [12]:
arr.nbytes

48

In [13]:
arr = np.array([[10, 20, 30], [40, 50, 60]], dtype=np.int32)
arr.nbytes  # each element takes 4 bytes. So, 3 * 6 = 24

24

In [14]:
np.zeros(5, dtype=np.int32)

array([0, 0, 0, 0, 0], dtype=int32)

In [15]:
np.zeros(5, dtype=np.float32)

array([0., 0., 0., 0., 0.], dtype=float32)

In [16]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.full(5, 3)

array([3, 3, 3, 3, 3])

In [20]:
np.full((4, 3), 7, dtype=np.int32)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]], dtype=int32)

In [21]:
np.empty((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [26]:
np.arange(2, 21, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
np.linspace(0, 10, 5, dtype=np.float32)

array([ 0. ,  2.5,  5. ,  7.5, 10. ], dtype=float32)

In [28]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
np.random.randint(1, 99)

67

In [30]:
np.random.randint(9, 99, size=3)

array([37, 85, 68])

In [31]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [36]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [38]:
arr1 = np.array([1, 2, 3])

arr2 = arr1

arr2[0] = 100

arr1, arr2

(array([100,   2,   3]), array([100,   2,   3]))

In [45]:
arr1 = np.arange(0, 1, 0.1)

view = arr1.view()

view[0] = 100.0

view, arr1

(array([100. ,   0.1,   0.2,   0.3,   0.4,   0.5,   0.6,   0.7,   0.8,
          0.9]),
 array([100. ,   0.1,   0.2,   0.3,   0.4,   0.5,   0.6,   0.7,   0.8,
          0.9]))

In [46]:
arr2 = np.arange(0, 1, 0.1)

cpy = arr2.copy()

cpy[0] = 100

cpy, arr2

(array([100. ,   0.1,   0.2,   0.3,   0.4,   0.5,   0.6,   0.7,   0.8,
          0.9]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]))

In [47]:
cpy.base

In [48]:
view.base

array([100. ,   0.1,   0.2,   0.3,   0.4,   0.5,   0.6,   0.7,   0.8,
         0.9])

In [49]:
np.shares_memory(arr1, view)

True

In [50]:
np.shares_memory(arr2, cpy)

False

In [51]:
arr1.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [52]:
view.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [53]:
cpy.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [54]:
arr = np.arange(10)
arr.flags["C_CONTIGUOUS"]

True

In [55]:
view = arr[::2]
view

array([0, 2, 4, 6, 8])

In [56]:
view.flags["C_CONTIGUOUS"]

False

In [57]:
view2 = arr[::2].copy()
view2

array([0, 2, 4, 6, 8])

In [ ]:
view2.flags["C_CONTIGUOUS"]

True

In [68]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [69]:
arr * 10

array([ 0, 10, 20, 30, 40, 50])

In [70]:
# The assignment creates another reference
arr *= 10
arr

array([ 0, 10, 20, 30, 40, 50])